version: '3'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  api:
    image: development:latest
    ports:
      - "8080:8080"
    environment:
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - ADDR=mysql
      - DBNAME=${DBNAME}
    depends_on:
      - mysql
    volumes:
      - .:/app/
    entrypoint: [ "/app/wait-for.sh", "mysql:3306", "--" ]
    command: [ "air", "-c", ".air.toml" ]
volumes:
  db-data:
