version: '3'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db-data:
